name: CI/CD

#pipeline gets executed on push to main/develop and on pull request
on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest #runs on a linux runner
    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
      - uses: actions/checkout@v4

      # Detect whether dev/terraform changed
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            terraform:
              - 'dev/terraform/**'

  build_and_deploy_code:
    #for normal code changes, just run the code scripts without re-reunning terraform
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - uses: actions/checkout@v4
      # Your normal code steps (backend/frontend/db/etc.)
      - name: Run backend script
        run: bash dev/backend/run_backend.sh

      - name: Run frontend script
        run: bash dev/frontend/run_frontend.sh

      - name: Run database script
        run: bash dev/database/run_database.sh

      - name: Read parameters
        run: cat dev/parameters/params.json


  terraform_plan:
    #plan and apply are separate steps to catch any tf errors in plan stage before applying. 
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.terraform == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: dev/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: dev/terraform
        run: terraform plan -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: dev/terraform/tfplan

  terraform_apply:
    runs-on: ubuntu-latest
    needs: [changes, terraform_plan]
    if: ${{ needs.changes.outputs.terraform == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    concurrency:
        #to make sure only one apply runs at a time. Subsequent pushes are queued, not executed simultaneously. 
      group: terraform-prod
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: dev/terraform

      - name: Terraform Init
        working-directory: dev/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: dev/terraform
        run: terraform apply -auto-approve tfplan
